# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      - name: update
        run: apt update
      - name: Install git
        run: apt install git
      - name: build cloundServer
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: |
            npm install
            npm run build:cloundServer
      - name: deploy
        run: |
          git clone https://github.com/JhonLandy/dockerDeploy.git
          cp -r docs/.vuepress/dist dockerDeploy/dist
          cd dockerDeploy
          git add .
          git commit -m 'deploy'
          git push

