# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VuePress CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setp NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build:cloundServer
        run: |
          npm ci
          npm run build:cloundServer
      - name: Git Config 
        run: |
          git config --global user.name "yuanchenglang"
          git config --global user.email "709364178@qq.com"
      - name: Copy files to cloundServer
        run: |
          git clone https://github.com/JhonLandy/dockerDeploy.git 
          cp -r ./docs/.vuepress/dist ./dockerDeploy
      - name: Commit files
        env:
          ACESS_TOKEN: ${{secrets.ACESS_TOKEN}}
        run: |
          cd dockerDeploy
          git add .
          git commit -m "deploy"
          rm -f ./.git/index.lock
          git push -f https://JhonLandy:$ACESS_TOKEN@github.com/JhonLandy/dockerDeploy.git
      - name: SSH DEPLOY
        env:
          HOST: ${{secrets.HOST}}
          PASSWORD: ${{secrets.PASSWORD}}
        uses:  appleboy/ssh-action@master
        with:
          host: $HOST
          username: 'root'
          password: $PASSWORD
          script: |
            cd dockerdemo/dockerDeploy
            sh deploy-dev.sh
      - name: build githubServer
        run: |
          npm run build:githubServer
      - name: Commit files
        env:
          ACESS_TOKEN: ${{secrets.ACESS_TOKEN}}
        run: |
          cd  docs/.vuepress/dist
          git init
          git add .
          git commit -m 'deploy'
          git remote add origin https://github.com/JhonLandy/blog.git
          git push -f https://JhonLandy:$ACESS_TOKEN@github.com/JhonLandy/blog.git
        
   