# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: build cloundServer
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build:cloundServer
      - name: Git Config 
        run: |
          git config --global user.name "yuanchenglang"
          git config --global user.email "709364178@qq.com"
      - name: Copy files to cloundServer
        run: |
          git clone https://github.com/JhonLandy/dockerDeploy.git 
          cp -r ./docs/.vuepress/dist ./dockerDeploy
      - name: Commit files
        env:
          GITHUB_TOKEN: ${{secrets.ACESS_TOKEN}}
        run: |
          cd dockerDeploy
          git add .
          git commit -m "deploy"
          git push -f https://JhonLandy:$GITHUB_TOKEN@github.com/JhonLandy/dockerDeploy.git
        
   