# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: build cloundServer
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build:cloundServer
      - name: Copy files
        run: |
          git clone https://github.com/JhonLandy/dockerDeploy.git 
          cp -r ./docs/.vuepress/dist ./dockerDeploy
      - name: Commit files
        run: |
          git config --global user.email "709364178@qq.com"
          git config --global user.name "yuanchenglang"
          cd ./dockerDeploy
          git add .
          git commit -m "deploy"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          repository: 'https://github.com/JhonLandy/dockerDeploy.git'
          branch: 'master' 
   
          