# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: build cloundServer
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - uses: srt32/git-actions@v0.0.3
      - name: git config & git clone
          with:
            args: [
              'git config --global user.name JhonLandy',
              'git config --global user.email 709364178@qq.com',
              'git clone https://github.com/JhonLandy/dockerDeploy.git'
            ]
      - name: deploy
        run: sh deploy.sh

