# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: build cloundServer
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build:cloundServer
      - name: Copy files
        run: |
          git clone https://github.com/JhonLandy/dockerDeploy.git 
          cp -r ./docs/.vuepress/dist ./dockerDeploy
      - name: Commit files
        run: |
          git config --global user.email "709364178@qq.com"
          git config --global user.name "709364178@qq.com"
          git config --list
          cd dockerDeploy
          ls
          git add .
          git commit -m "deploy"
          git remote set-url origin https://709364178@qq.com:yuan794478148@github.com/JhonLandy/dockerDeploy.git
          git push -u origin master
   